### ISSUE TITLE
Laura Gerhardt cannot log into production

### ISSUE THREAD

**Issue by adelevie** [18F/micropurchase#528]
logs:

```
2016-05-11T12:37:35.31-0400 [App/0]      OUT 16:37:35 web.1    | Processing by AuthenticationsController#create as HTML
2016-05-11T12:37:35.31-0400 [App/0]      OUT 16:37:35 web.1    |   Parameters: {"code"=>"[paranoid redaction]", "state"=>"[paranoid redaction]", "provider"=>"github"}
2016-05-11T12:37:35.31-0400 [App/0]      OUT 16:37:35 web.1    |   User Load (1.3ms)  SELECT  "users".* FROM "users" WHERE "users"."github_id" = $1 LIMIT 1  [["github_id", "5840989"]]
2016-05-11T12:37:35.32-0400 [App/0]      OUT 16:37:35 web.1    |    (0.9ms)  BEGIN
2016-05-11T12:37:35.32-0400 [App/0]      OUT 16:37:35 web.1    |    (0.8ms)  ROLLBACK
2016-05-11T12:37:35.32-0400 [App/0]      OUT 16:37:35 web.1    | Completed 422 Unprocessable Entity in 5ms (ActiveRecord: 3.0ms)
2016-05-11T12:37:35.32-0400 [App/0]      OUT 16:37:35 web.1    | 
2016-05-11T12:37:35.32-0400 [App/0]      OUT 16:37:35 web.1    | ActiveRecord::RecordInvalid (Validation failed: DUNS number format is invalid):
2016-05-11T12:37:35.32-0400 [App/0]      OUT 16:37:35 web.1    |   app/models/user.rb:14:in `from_oauth_hash'
2016-05-11T12:37:35.32-0400 [App/0]      OUT 16:37:35 web.1    |   app/models/login_user.rb:3:in `perform'
2016-05-11T12:37:35.32-0400 [App/0]      OUT 16:37:35 web.1    |   app/controllers/authentications_controller.rb:3:in `create'
2016-05-11T12:37:35.32-0400 [App/0]      OUT 16:37:35 web.1    | 

```

**Comment by jessieay** [comment]
I think this might be fixed via https://github.com/18F/micropurchase/pull/533/files -- let's deploy to prod and find out!

**Comment by jessieay** [comment]
also made this update which I think might have been causing the problem https://github.com/18F/micropurchase/pull/550/files

**Comment by jessieay** [comment]
Just deployed to prod and confirmed with Laura that she can log in on prod. closing
